version: '3.1'

services:
  seed:
    #image: colinmollenhour/mariadb-galera-swarm:10.1
    image: rbnor/mariadbcluster
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=bookface
      - MYSQL_USER=bookfaceuser
      - MYSQL_PASSWORD=somepassword
      - NODE_ADDRESS=^10.10.*.*
    networks:
      - galera_network
    #restart: always
    command: seed
    #ports:
     # - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - xtrabackup_password
      - mysql_password
      - mysql_root_password
  node:
    #image: colinmollenhour/mariadb-galera-swarm:10.1
    image: rbnor/mariadbcluster
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - NODE_ADDRESS=^10.10.*.*
      - HEALTHY_WHILE_BOOTING=1
    networks:
      - galera_network
    command: node seed,node
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      replicas: 0
    #ports:
     # - "3306:3306"
    secrets:
      - xtrabackup_password

  memcached:
    image: rbnor/bookfacememcached
    ports:
      - "11211:11211"
  web:
    restart: always
    image: rbnor/web
    #links:
     # - mariadb
     # - memcached
    ports:
      - "80:80"
    environment:
      - DATABASE_HOST='mysql'
      - DATABASE_NAME='bookface'
      - DATABASE_USER='bookfaceuser'
      - DATABASE_PASSWORD='somepassword'
      - container_name=web

volumes:
  mysql-data:
    driver: local

networks:
  galera_network:
    driver: overlay

secrets:
  xtrabackup_password:
    file: /home/ubuntu/.secrets/xtrabackup_password
  mysql_password:
    file: /home/ubuntu/.secrets/mysql_password
  mysql_root_password:
    file: /home/ubuntu/.secrets/mysql_root_password



